### ISSUE TITLE
Fax wird 2x gesendet

### ISSUE THREAD

**Issue by michamilz** [okfde/froide-fax#1]
Vielen Dank für dieses tolle Addon!!elf!

https://fragdenstaat.de/anfrage/blockaden-auf-twitterkanal-der-polizei-schwerin-1/

Nach dem absenden der Anfrage kommt der Screen mit dem Papierflieger. Klicke ich auf den Link zur Anfrage, erscheint über der Anfrage die Aufforderung meine Unterschrift zu hinterlegen und das Fax zu versenden. Die Unterschrift war bereits hinterlegt. Nach dem Klick auf den Button zum Speichern und Fax versenden erscheint der Dialog wieder und wurde wieder bestätigt. Danach noch einmal. Erst dann kam der Hinweis auf den Versand des Faxes. In der Historie erscheinen jetzt 2 Faxe.

**Comment by stefanw** [comment]
Ich glaube, das ist mittlerweile behoben. Die Fax-Nachricht wird jetzt sofort erstellt und der Anhang wird im Hintergrund generiert und verschickt.
